positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["com.docker.compose.project=image-optimizer"]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_service"]
        target_label: "service"
      - source_labels:
          ["__meta_docker_container_label_com_docker_compose_project"]
        target_label: "project"
    pipeline_stages:
      - json:
          expressions:
            time: time
            level: level
            component: component
            message: message
      - labels:
          level:
          component:
      - timestamp:
          source: time
          format: RFC3339Nano
