global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "image-optimizer-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "image-optimizer-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9091"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8888"]
